---
# The hostname/IP of your broker
mqtt_broker: homeassistant.home.arpa
# If you have a custom Home Assistant discovery prefix, set it here
discovery_prefix: homeassistant
# How often to send periodic updates, in seconds
update_interval: 30
# MQTT login information
mqtt_username: username
mqtt_password: password
# Bluetooth adapter information.
# Optional, uncomment and provide your adapter name to pick a specific device.
# Find the adapter name with `hciconfig` or similar.
#adapter: hci0
